@startuml Entidad-relacion
' Configuración estilo
skinparam class {
  BackgroundColor LightSkyBlue
  ArrowColor DeepSkyBlue
  BorderColor Navy
}

' Entidades principales
entity "Materia" as materia {
  *materia_id : string <<PK>>
  --
  nombre_materia : string
  horas_semanales_tipicas : integer
  tipo_materia : string
  seccion : string
  cantidad_docente : integer
}

entity "Curso" as curso {
  *curso_id : string <<PK>>
  --
  nombre_curso : string
  nivel : string
  horario_entrada : time
  horario_salida : time
  inscritos : integer
}

entity "Profesor" as profesor {
  *profesor_id : integer <<PK>>
  --
  nombre : string
  apellido : string
  seccion : string
  categoria : string
}

entity "Sala" as sala {
  *sala_id : string <<PK>>
  --
  capacidad : integer
  tipo_sala : string
  nombre_nivel : string
}

' Entidades operativas
entity "Detalle_materia" as detalle_materia {
  *requisito_id : integer <<PK>>
  --
  *curso_id : string <<FK>>
  *materia_id : string <<FK>>
  frecuencia_semanal : integer
  duracion_sesion_horas : decimal
}

entity "Clase" as clase {
  *clase_id : string <<PK>>
  --
  *materia_id : string <<FK>>
  *profesor_id : integer <<FK>>
  *sala_id : string <<FK>>
  dia_semana : string
  hora_inicio : time
  hora_fin : time
  *requisito_id : integer <<FK>>
}

entity "Dia_operativo_curso" as dia_operativo {
  *curso_id : string <<FK>>
  --
  lunes : boolean
  martes : boolean
  miercoles : boolean
  jueves : boolean
  viernes : boolean
}

' Tablas intermedias (relaciones muchos a muchos)
entity "Profesor_materia" as profesor_materia {
  *profesor_id : integer <<FK>>
  *materia_id : string <<FK>>
}

entity "Clase_compartida" as clase_compartida {
  *materia_id : string <<FK>>
  --
  clase_compartida : string
}

' Relaciones
materia "1" -- "0..*" detalle_materia : implementada en
materia "1" -- "0..*" clase : se imparte como
materia "1" -- "0..*" profesor_materia : es impartida por
materia "1" -- "0..*" clase_compartida : comparte con

curso "1" -- "0..*" detalle_materia : contiene
curso "1" -- "1" dia_operativo : opera en

profesor "1" -- "0..*" clase : imparte
profesor "1" -- "0..*" profesor_materia : puede impartir

sala "1" -- "0..*" clase : alberga

detalle_materia "1" -- "0..*" clase : programa
@enduml